### ISSUE TITLE
Ruby 2.5.1 not supported ?

### ISSUE THREAD

**Issue by epetre** [marcel/aws-s3#120]
seems to be pointing towards an issue there: https://github.com/marcel/aws-s3/blob/master/lib/aws/s3/extensions.rb#L222

https://gyazo.com/eea1595aafa6d094c315b65e3f88fa77.png

14:42:37 worker.1 | /Users/me/.rvm/gems/ruby-2.5.1/gems/aws-s3-0.6.3/lib/aws/s3/extensions.rb:223:in `class_eval': /Users/me/.rvm/gems/ruby-2.5.1/gems/aws-s3-0.6.3/lib/aws/s3/extensions.rb:223: `@@{' is not allowed as a class variable name (SyntaxError)
14:42:37 worker.1 | /Users/me/.rvm/gems/ruby-2.5.1/gems/aws-s3-0.6.3/lib/aws/s3/extensions.rb:223: syntax error, unexpected end-of-input
14:42:37 worker.1 |         unless defined? @@{:default=>{"ActionController...

**Comment by Linell** [comment]
Not on 2.5.1, but I'm encountering the same problem:

```
/Users/linell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/aws-s3-0.6.3/lib/aws/s3/extensions.rb:223:in `class_eval': /Users/linell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/aws-s3-0.6.3/lib/aws/s3/extensions.rb:223: `@@{' is not allowed as a class variable name
/Users/linell/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/aws-s3-0.6.3/lib/aws/s3/extensions.rb:223: syntax error, unexpected end-of-input
        unless defined? @@{:instance_writer=>false, :ins
                          ^ (SyntaxError)
```
